name: watermeter_postgraduate
description: Traintime PDA postgraduate edition.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.3

environment:
  sdk: ">=3.0.0"


dependencies:
  # Network
  dio: ^5.0.0
  crypto: ^3.0.2
  encrypt: ^5.0.1
  # Stroage Cache
  shared_preferences: ^2.0.15
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.5
  path_provider: ^2.0.11
  file_picker: ^5.2.5
  json_annotation: ^4.8.0
  # Deal with html
  beautiful_soup_dart: ^0.3.0
  # Setting
  settings_ui: ^2.0.2
  # Homepage and others
  easy_refresh: ^3.3.0+1
  # Others
  url_launcher: ^6.1.6
  jiffy: ^6.2.1
  icalendar_parser: any
  auto_size_text: ^3.0.0
  talker_dio_logger: ^2.1.2
  intl: ^0.18.0
  styled_widget: any
  sn_progress_dialog:
  ming_cute_icons:
  fluttertoast:
  alice:
  get:
  flutter_staggered_grid_view:

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.7.1


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    # Easter egg for ironic things, long live Futurama!
    - assets/Farnsworth-Class.jpg
    - assets/Humpy-Score.jpg
    - assets/Login-Background.jpg
    - assets/Boochi-Afraid-Work.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
